FROM java:8-jre-alpine

RUN echo -e "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main\n\
https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" > /etc/apk/repositories

RUN apk --update add curl bash ttf-dejavu libgcc libc6-compat &&\
      rm -rf /var/cache/apk/*

EXPOSE 8080