#global 
#!!!Must can't be removed
Registry_url: ##Registry_url##
Registry_user: ##Registry_user##
Registry_password: ##Registry_password##
Hub_secret: ##Hub_secret_value##
Registry_type: ##Registry_type##
Image_tag_suffix: ##IMAGE_TAG_SUFFIX##
Target_registry: ecr
Image_tag: ##IMAGE_TAG##


#specific
Salix_nfs_server: 9dc0d4bd4d-duc16.cn-zhangjiakou.nas.aliyuncs.com
Salix_nfs_basepath: /spacefood
FE_base_registry: ecr

