FROM alpine:3.7

RUN echo -e 'http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.7/main\nhttp://mirrors.tuna.tsinghua.edu.cn/alpine/v3.7/community' > /etc/apk/repositories
RUN apk add --no-cache \
	openssh \
    bash \
    curl \
    mysql-client

#RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
#    chmod +x ./kubectl && \
#    mv ./kubectl /usr/local/bin/kubectl

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.11.2/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

WORKDIR /home

ENTRYPOINT ["/bin/bash"]
