apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: common
spec:
  type: NodePort
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
    nodePort: 32021
  selector:
    common.service: mysql