#global
#global 
#!!!Must can't be removed
Registry_url: ##Registry_url##
Registry_user: ##Registry_user##
Registry_password: ##Registry_password##
Hub_secret: ##Hub_secret_value##
Registry_type: ##Registry_type##
Image_tag_suffix: ##IMAGE_TAG_SUFFIX##
Target_registry: ecr
Image_tag: ##IMAGE_TAG##
Node_external_ip_for_nodeport: 39.98.242.76

#monitor
Monitor_prometheus_hostpath: /home/ubuntu/opt/prometheus
Monitor_alertmanager_dingtalk_webhook: https://oapi.dingtalk.com/robot/send?access_token=700c3965997e22fd52ac91a8f9105a825c369108c3d330bb2258ff26d9d268a4

#mysql
mysql_storage: 50G