apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-slave
  namespace: redis-default
spec:
  serviceName: redis-slave
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis-slave
          image: 370307265965.dkr.ecr.cn-north-1.amazonaws.com.cn/chainnova/redis:4.0.6
          imagePullPolicy: Always
          env:
            - name: PASSWORD
              value: "123456"
          ports:
            - containerPort: 6379
              name: redis-slave
          readinessProbe:
            exec:
              command: ['redis-cli','-a','123456', 'info', 'server']
          volumeMounts:
            - name: redis-slave-storage
              mountPath: /data
      volumes:
        - name: redis-slave-storage
          emptyDir: {}
