apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  type: NodePort
  ports:
  - name: "alertmanager"
    port: 9093
    targetPort: 9093
    nodePort: 31027
  - name: "dingtalk-webhook"
    port: 8060
    targetPort: 8060
    nodePort: 31028
  selector:
    baas.mon.service: alertmanager
