apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
  - name: "grafana"
    port: 3000
    targetPort: 3000
    nodePort: 31026
  selector:
    baas.mon.service: grafana
