apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    baas.mon.service: node-exporter
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  clusterIP: None
  type: ClusterIP
