apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: "prometheus"
    port: 9090
    targetPort: 9090
    nodePort: 31016
  selector:
    baas.mon.service: prometheus
