apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "mariadb-pv" 
  labels:
    app: mariadb-pv
    type: amazonEBS
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-0e1e8cc868a7cfcf1"
