kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pvc
  namespace: chainnova
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: wordpress-pv
