apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "wordpress-pv" 
  labels:
    app: wordpress-pv
    type: amazonEBS
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-0104436e6e4001a76"
